///|
priv suberror EmptyArrayError String derive(Show)

///|
suberror InconsistentSeriesLength String derive(Show)

///|
priv suberror DuplicateColumnError String derive(Show)

///|
suberror ColumnNotFoundError String derive(Show)

///|
suberror IndexOutOfBounds String derive(Show)

///|
suberror InvalidType String derive(Show)

///|
priv suberror PathNotFound String derive(Show)

///|
priv suberror NotCSVFile String derive(Show)

// suberror TypeError String derive(Show)
