///|
priv type! EmptyArrayError String derive(Show)

///|
type! InconsistentSeriesLength String derive(Show)

///|
priv type! DuplicateColumnError String derive(Show)

///|
type! ColumnNotFoundError String derive(Show)

///|
type! IndexOutOfBounds String derive(Show)

///|
type! InvalidType String derive(Show)

///|
priv type! PathNotFound String derive(Show)

///|
priv type! NotCSVFile String derive(Show)

// type! TypeError String derive(Show)
